# Dependencies
markdown:         kramdown
highlighter:      rogue

# Features
categories: "data-analysis|finance|stats|programming|machine-learning"
excerpt_separator: <!--more-->

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            Positive Analysis
tagline:          ''
description:      'Oscar Thelander'
url:              / 
baseurl:          /
imageurl:         '/public/'

author:
  name:           'Oscar Thelander'
  email:          'oscarga.thelander@gmail.coms'

social:
  linkedin: https://www.google.com

paginate:         10

# Custom vars
version:          2.1.0

gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
plugins: [jekyll-paginate]
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
github:
  repo: https://github.com/oscthe/